export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const LOADING_STARTED = "LOADING_STARTED";
export const LOADING_FINISHED = "LOADING_FINISHED";
